# Quick syntax check:
# python -c 'import sys, yaml; yaml.dump (yaml.load (sys.stdin), sys.stdout)' <.gitlab-ci.yml

# If things don't seem to work, this can help:
# https://gitlab.gnome.org/GNOME/libnma/-/ci/lint

.fedora_minimal: &fedora_minimal
  before_script:
    - dnf -y install $EXTRA_PACKAGES
      file
      findutils
      gcc
      desktop-file-utils
      gettext-devel
      glib2-devel
      gtk3-devel
      NetworkManager-libnm-devel
      pkgconfig
      gawk
      /usr/bin/autopoint

.fedora_full: &fedora_full
  before_script:
    - dnf -y install $EXTRA_PACKAGES
      file
      findutils
      gcc
      desktop-file-utils
      gettext-devel
      glib2-devel
      gtk3-devel
      gtk4-devel
      NetworkManager-libnm-devel
      pkgconfig
      /usr/bin/vapigen
      /usr/bin/autopoint
      gobject-introspection-devel redhat-rpm-config
      gtk-doc
      iso-codes-devel
      mobile-broadband-provider-info-devel

.dist: &dist
  dependencies:
    - fedora42_dist
  variables:
    GIT_STRATEGY: none

.fedora_meson_minimal: &fedora_meson_minimal
  <<: *fedora_minimal
  <<: *dist
  script:
    - tar xJf libnma-*.tar.xz
    - dnf -y install meson
    - meson $EXTRA_MESON_FLAGS
      -Dgcr=false
      -Diso_codes=false
      -Dmobile_broadband_provider_info=false
      -Dld_gc=false
      -Dgtk_doc=false
      -Dintrospection=false
      -Dvapi=false
      -Dmore_asserts=no
      libnma-*/ build
    - ninja -v -C build
    - ninja -v -C build test
    - ninja -v -C build install
    - ninja -v -C build uninstall

.fedora_meson_full: &fedora_meson_full
  <<: *fedora_full
  <<: *dist
  script:
    - dnf -y install meson
    - tar xJf libnma-*.tar.xz
    - meson $EXTRA_MESON_FLAGS
      -Dlibnma_gtk4=true
      -Dgcr=true
      -Diso_codes=true
      -Dmobile_broadband_provider_info=true
      -Dld_gc=true
      -Dgtk_doc=true
      -Dintrospection=true
      -Dvapi=true
      -Dmore_asserts=yes
      libnma-*/ build
    - ninja -v -C build
    - ninja -v -C build test
    - ninja -v -C build install
    - ninja -v -C build uninstall

.fedora_autotools_minimal: &fedora_autotools_minimal
  <<: *fedora_minimal
  <<: *dist
  script:
    - dnf -y install make
    - tar xJf libnma-*.tar.xz
    - cd libnma-*/
    # Sometimes the CI builder clocks are skewed.
    # Make sure the dst files are not from future.
    - find | xargs touch
    - ./configure $EXTRA_CONFIGURE_FLAGS
      --disable-silent-rules
      --with-more-asserts=no
      --disable-nls
      --disable-iso-codes
      --disable-mobile-broadband-provider-info
      --disable-gtk-doc
      --disable-introspection
      --disable-vala
      --disable-more-warnings
      --without-libnma-gtk4
      --without-gcr
    - make -j$(nproc)
    - make -j$(nproc) check
    - make -j$(nproc) install
    - make -j$(nproc) uninstall

.fedora_autotools_full: &fedora_autotools_full
  <<: *fedora_full
  <<: *dist
  script:
    - dnf -y install make
    - tar xJf libnma-*.tar.xz
    - cd libnma-*/
    # Sometimes the CI builder clocks are skewed.
    # Make sure the dst files are not from future.
    - find | xargs touch
    - ./configure $EXTRA_CONFIGURE_FLAGS
      --disable-silent-rules
      --with-more-asserts=yes
      --enable-nls
      --enable-iso-codes
      --enable-mobile-broadband-provider-info
      --enable-gtk-doc
      --enable-introspection
      --enable-vala
      --enable-more-warnings
      --with-libnma-gtk4
      --with-gcr
    - make -j$(nproc)
    - make -j$(nproc) check
    - make -j$(nproc) install
    - make -j$(nproc) uninstall

.centos_meson: &centos_meson
  before_script:
    - dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-${CENTOS_VERSION}.noarch.rpm
    - dnf install -y 'dnf-command(config-manager)'
    - dnf config-manager --set-enabled crb
    - dnf -y install
      file
      findutils
      gcc
      desktop-file-utils
      gettext-devel
      glib2-devel
      gtk3-devel
      gtk4-devel
      intltool
      NetworkManager-libnm-devel
      pkgconfig
      /usr/bin/vapigen
      gcr-devel
      gobject-introspection-devel
      redhat-rpm-config
      gtk-doc
      iso-codes-devel
      mobile-broadband-provider-info-devel
  script:
    - dnf -y install meson
    - tar xf libnma-*.tar.xz
    - meson $EXTRA_MESON_FLAGS
      -Dlibnma_gtk4=true
      -Dgcr=true
      -Diso_codes=true
      -Dmobile_broadband_provider_info=true
      -Dld_gc=true
      -Dgtk_doc=true
      -Dintrospection=true
      -Dvapi=true
      -Dmore_asserts=yes
      libnma-*/ build
    - ninja -v -C build
    - ninja -v -C build test
    - ninja -v -C build install
    - ninja -v -C build uninstall

fedora42_dist:
  <<: *fedora_full
  image: fedora:42
  stage: build
  script:
    - dnf -y install
      autoconf automake make gcr-devel
      xorg-x11-server-Xvfb xorg-x11-xinit
    - sh autogen.sh
    # The Xvfb dance below is because of
    # https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4415
    - xinit /bin/sh -c 'make -j$(nproc) distcheck && touch .success' -- /usr/bin/Xvfb :5
    - test -e .success
  artifacts:
    paths:
      - "*.xz"

fedora_meson_minimal:
  <<: *fedora_meson_minimal
  image: fedora:latest
  stage: test

fedora_meson_full:
  <<: *fedora_meson_full
  variables:
    EXTRA_PACKAGES: gcr-devel
  image: fedora:latest
  stage: test

fedora_autotools_minimal:
  <<: *fedora_autotools_minimal
  image: fedora:latest
  stage: test

fedora_autotools_full:
  <<: *fedora_autotools_full
  variables:
    EXTRA_PACKAGES: gcr-devel
  image: fedora:latest
  stage: test

centos9_meson_full:
  <<: *dist
  <<: *centos_meson
  variables:
    CENTOS_VERSION: 9
  image: quay.io/centos/centos:stream9
  stage: test

centos10_meson_full:
  <<: *dist
  <<: *centos_meson
  variables:
    CENTOS_VERSION: 10
  image: quay.io/centos/centos:stream10
  stage: test

# https://libnma.pages.gitlab.gnome.org/libnma/
pages:
  <<: *fedora_full
  <<: *dist
  image: fedora:latest
  stage: deploy
  script:
    - dnf -y install make
    - tar xJf libnma-*.tar.xz
    - cd libnma-*/
    # Sometimes the CI builder clocks are skewed.
    # Make sure the dst files are not from future.
    - find | xargs touch
    - ./configure
      --disable-silent-rules
      --enable-gtk-doc
    - make -j$(nproc)
    - cd ..
    - mv libnma-*/html public
  artifacts:
    paths:
      - public
  only:
    - main
